const REQUEST_ID = {
    MESSAGE_SUBSCRIPTION: 1,
    UPDATE_AGENT_STATUS: 2,
    SEND_MESSAGE: 3,
    GET_DEPARTMENTS: 4,
    TRANSFER_TO_DEPARTMENT: 5,
    SEND_QUICK_REPLIES: 6,
    SEND_PANEL_TEMPLATES: 7,
    ADD_TAGS: 8
};

module.exports ={
    REQUEST_ID
}
